Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.box_check_update = false

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../site.yml"
    ansible.verbose = "v"
    ansible.groups = {
      "all" => ["default"],
    }
  end
end
