---
- name: Add RPM key
  rpm_key:
    state: present
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7

- name: install epel
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - epel-release

- name: install basic packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - docker
    - python-pip 
    - nc

- name: install docker-py
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    state: present
  with_items:
    - { name: docker-compose, version:  "{{ DOCKER_COMPOSE_VERSION }}" }
    - { name: docker-py, version: "{{ DOCKER_PY_VERSION }}" }
